package com.emarsys.networking.clients.embedded.messaging.model

import kotlinx.serialization.Serializable

@Serializable
data class MetaData(
    val version: String,
    val labels: Labels,
    val design: DesignMetaData?
)

@Serializable
data class Labels(
    val allMessagesHeader: String,
    val unreadMessagesHeader: String,
    val filterCategories: String,
    val pinnedMessagesTitle: String,
    val detailedMessageCloseButton: String,
    val deleteDetailedMessageButton: String,
    val emptyStateTitle: String,
    val emptyStateDescription: String
)

@Serializable
data class DesignMetaData(
    val fillColor: FillColors?,
    val text: TextMetaData?,
    val misc: Misc?
)

@Serializable
data class FillColors(
    val primary: String,
    val onPrimary: String,
    val primaryContainer: String,
    val onPrimaryContainer: String,
    val secondary: String,
    val onSecondary: String,
    val secondaryContainer: String,
    val onSecondaryContainer: String,
    val tertiary: String,
    val onTertiary: String,
    val tertiaryContainer: String,
    val onTertiaryContainer: String,
    val error: String,
    val onError: String,
    val errorContainer: String,
    val onErrorContainer: String,
    val background: String,
    val onBackground: String,
    val surface: String,
    val onSurface: String,
    val surfaceVariant: String,
    val onSurfaceVariant: String,
    val surfaceContainer: String,
    val surfaceContainerHigh: String,
    val surfaceContainerHighest: String,
    val surfaceContainerLow: String,
    val surfaceContainerLowest: String,
    val surfaceDim: String,
    val surfaceBright: String,
    val outline: String,
    val outlineVariant: String,
    val inverseSurface: String,
    val inverseOnSurface: String,
    val inversePrimary: String,
    val scrim: String,

    val selectedState: String,
    val disabledState: String,
    val hoverState: String,
    val pressedState: String,
    val focusState: String,

    val warning: String,
    val onWarning: String,
    val warningContainer: String,
    val onWarningContainer: String,
    val success: String,
    val onSuccess: String,
    val successContainer: String,
    val onSuccessContainer: String,
    val info: String,
    val onInfo: String,
    val infoContainer: String,
    val onInfoContainer: String
)

@Serializable
data class TextMetaData(
    val displayLargeFontSize: Double,
    val displayMediumFontSize: Double,
    val displaySmallFontSize: Double,
    val headlineLargeFontSize: Double,
    val headlineMediumFontSize: Double,
    val headlineSmallFontSize: Double,
    val titleLargeFontSize: Double,
    val titleMediumFontSize: Double,
    val titleSmallFontSize: Double,
    val bodyLargeFontSize: Double,
    val bodyMediumFontSize: Double,
    val bodySmallFontSize: Double,
    val labelLargeFontSize: Double,
    val labelMediumFontSize: Double,
    val labelSmallFontSize: Double,
)

@Serializable
data class Misc(
    val dialogCornerRadius: Double,
    val categoryButtonCornerRadius: Double,
    val messageItemCornerRadius: Double,
    val filterButtonCornerRadius: Double,
    val actionButtonCornerRadius: Double,
    val chipCornerRadius: Double,
    val detailViewCornerRadius: Double,
    val headerCornerRadius: Double,
    val footerCornerRadius: Double,
    val modalCornerRadius: Double,
    val snackbarCornerRadius: Double,
    val tooltipCornerRadius: Double,
    val badgeCornerRadius: Double,
    val avatarCornerRadius: Double,
    val imageCornerRadius: Double,

    val messageItemPadding: Double,
    val messageItemMargin: Double,
    val messageItemSpacing: Double,
    val dialogPadding: Double,
    val dialogMargin: Double,
    val dialogSpacing: Double,
    val categoryButtonPadding: Double,
    val categoryButtonMargin: Double,
    val categoryButtonSpacing: Double,
    val filterButtonPadding: Double,
    val filterButtonMargin: Double,
    val actionButtonPadding: Double,
    val actionButtonMargin: Double,
    val headerPadding: Double,
    val headerMargin: Double,
    val headerSpacing: Double,
    val footerPadding: Double,
    val footerMargin: Double,
    val footerSpacing: Double,
    val listPadding: Double,
    val listMargin: Double,
    val listSpacing: Double,
    val detailViewPadding: Double,
    val detailViewMargin: Double,
    val detailViewSpacing: Double,

    val dividerWidth: Double,
    val dividerColor: String,
    val categoryButtonStrokeColor: String,
    val categoryButtonStrokeSize: Double,
    val messageItemStrokeColor: String,
    val messageItemStrokeSize: Double,
    val filterButtonStrokeColor: String,
    val filterButtonStrokeSize: Double,
    val actionButtonStrokeColor: String,
    val actionButtonStrokeSize: Double,

    val messageItemElevation: Double,
    val dialogElevation: Double,
    val categoryButtonElevation: Double,
    val filterButtonElevation: Double,
    val actionButtonElevation: Double,
    val headerElevation: Double,
    val footerElevation: Double,
    val modalElevation: Double,
    val snackbarElevation: Double,
    val tooltipElevation: Double,

    val messageItemIconSize: Double,
    val categoryButtonIconSize: Double,
    val filterButtonIconSize: Double,
    val actionButtonIconSize: Double,
    val headerIconSize: Double,
    val footerIconSize: Double,
    val dialogIconSize: Double,
    val snackbarIconSize: Double,
    val tooltipIconSize: Double,
    val listContentPadding: Double,
    val listItemSpacing: Double,
    val listItemMargin: Double,
    val tabButtonPadding: Double,
    val tabButtonSpacing: Double,
    val filterButtonSpacing: Double,
    val actionButtonSpacing: Double,
    val compactOverlayWidth: Double,
    val compactOverlayMaxHeight: Double,
    val compactOverlayPadding: Double,
    val compactOverlaySpacing: Double,
    val compactOverlayCornerRadius: Double,
    val compactOverlayElevation: Double,
    val emptyStatePadding: Double,
    val emptyStateSpacing: Double,
    val emptyStateIconPadding: Double,
    val detailViewImageHeight: Double,
    val detailViewImageCornerRadius: Double,
    val detailViewTagPadding: Double,
    val detailViewTagSpacing: Double,
    val detailViewActionSpacing: Double,
    val swipeDeleteBackgroundCornerRadius: Double,
    val swipeDeleteButtonSize: Double,
    val swipeDeleteButtonCornerRadius: Double,
    val swipeDeleteIconSize: Double
)