package com.emarsys

object SdkConstants {
    const val PUSH_CLICKED_EVENT_NAME = "push:click"
    const val BUTTON_CLICK_ORIGIN = "button"
    const val CLIENT_ID_STORAGE_KEY = "clientId"
    const val IN_APP_BUTTON_CLICKED_EVENT_NAME = "click"
    const val SILENT_PUSH_RECEIVED_EVENT_NAME = "push:silentPushReceived"
    const val SESSION_START_EVENT_NAME = "session:start"
    const val SESSION_END_EVENT_NAME = "session:end"
    const val APP_START_EVENT_NAME = "app:start"
    const val CHANGE_APP_CODE_NAME = "changeApplicationCode"
    const val LINK_CONTACT_NAME = "linkContact"
    const val LINK_AUTHENTICATED_CONTACT_NAME = "linAuthenticatedContact"
    const val UNLINK_CONTACT_NAME = "unlinkContact"
    const val TRACK_DEEPLINK_NAME = "trackDeepLink"
    const val INAPP_VIEWED_EVENT_NAME = "inapp:viewed"
    const val ON_EVENT_ACTION_REPORTING_EVENT_NAME = "on_event:action"
    const val ON_EVENT_ACTION_ORIGIN = "onEventAction"
    const val DISMISS_EVENT_NAME = "dismiss"
    const val REREGISTRATION_REQUIRED_EVENT_NAME = "reregistrationRequired"
    const val REGISTER_DEVICE_INFO_EVENT_NAME = "registerDeviceInfo"
    const val DEVICE_INFO_READY_EVENT_NAME = "DeviceInfoReady"
    const val REGISTER_PUSH_TOKEN_EVENT_NAME = "registerPushToken"
    const val CLEAR_PUSH_TOKEN_EVENT_NAME = "clearPushToken"
    const val REMOTE_CONFIG_UPDATE_REQUIRED_EVENT_NAME = "remoteConfigUpdateRequired"
    const val APPLY_APPCODE_BASED_REMOTE_CONFIG_EVENT_NAME = "applyAppCodeBasedRemoteConfig"
    const val APPLY_GLOBAL_REMOTE_CONFIG_EVENT_NAME = "applyGlobalRemoteConfig"
    const val LOG_EVENT_NAME = "log"
    const val METRIC_EVENT_NAME = "metric"
    const val EMS_DEEP_LINK_TRACKED_KEY = "ems_deep_link_tracked"

    const val MOBILE_PLATFORM_CATEGORY = "mobile"
    const val WEB_PLATFORM_CATEGORY = "web"

    const val UNKNOWN_WRAPPER_INFO = "unknown"

    const val LANGUAGE_STORAGE_KEY = "customerOverwroteLanguageCodeKey"
    const val DEVICE_INFO_UPDATE_REQUIRED_EVENT_NAME = "deviceInfoUpdateRequired"
    const val PAGE_LOCATION_ATTRIBUTE_KEY = "url"
}