package com.emarsys.core.url

enum class EmarsysUrlType {
    LINK_CONTACT,
    UNLINK_CONTACT,
    REFRESH_TOKEN,
    PUSH_TOKEN,
    EVENT,
    REGISTER_DEVICE_INFO,
    REMOTE_CONFIG_SIGNATURE,
    REMOTE_CONFIG,
    GLOBAL_REMOTE_CONFIG_SIGNATURE,
    GLOBAL_REMOTE_CONFIG,
    DEEP_LINK
}