package com.emarsys.core.url

internal enum class EmarsysUrlType {
    CHANGE_APPLICATION_CODE,
    LINK_CONTACT,
    UNLINK_CONTACT,
    REFRESH_TOKEN,
    CHANGE_MERCHANT_ID,
    PUSH_TOKEN,
    EVENT,
    REGISTER_DEVICE_INFO,
    REMOTE_CONFIG_SIGNATURE,
    REMOTE_CONFIG,
    GLOBAL_REMOTE_CONFIG_SIGNATURE,
    GLOBAL_REMOTE_CONFIG,
    DEEP_LINK,
    LOGGING,
    FETCH_EMBEDDED_MESSAGES,
    FETCH_BADGE_COUNT
}